### ISSUE TITLE
Fail to run ConsoleApplication1.exe on win10 x64

### ISSUE THREAD

**Issue by Merryang** [tianoak/MedicalImageFormatConvert#1]
when I ran **ConsoleApplication1.exe**, the fatal errors were caused by missing of dll files, including MSVCP140D.dll, VCRUNTIME140.dll and ucrtbased.dll . And after reinstalling it, still not worked. Can you help to solve the problem,thanks very much.
![image](https://user-images.githubusercontent.com/36835678/42209986-a7c53d6e-7ee2-11e8-9e33-1603be86f493.png)

**Comment by tianoak** [comment]
Hello,

I am sorry I have no idea why these errors occurred. I have not used it for a long time. But, it looks like common problems. You can search it on Internet. Maybe it has something to do with the version of VS, as I remember, mine was vs2015.

Good luck to you. Hope you can solve it soon.

best,
Tian
________________________________
发件人: Merryang <notifications@github.com>
发送时间: 2018年7月3日 9:01:14
收件人: tianoak/MedicalImageFormatConvert
抄送: Subscribed
主题: [tianoak/MedicalImageFormatConvert] Fail to run ConsoleApplication1.exe on win10 x64 (#1)


when I ran ConsoleApplication1.exe, the fatal errors were caused by missing of dll files, including MSVCP140D.dll, VCRUNTIME140.dll and ucrtbased.dll . And after reinstalling it, still not worked. Can you help to solve the problem,thanks very much.
[image]<https://user-images.githubusercontent.com/36835678/42209986-a7c53d6e-7ee2-11e8-9e33-1603be86f493.png>

―

**Comment by Merryang** [comment]
Hello Tian,
    I haven't got a VS before, and following your answer, I installed the newest VS 2017 last night, and dll files can be found. However, new errors appeared, is it that I must have VS 2015 instead of VS 2017? Here is a runtime screen shot. 
![image](https://user-images.githubusercontent.com/36835678/42486264-acd10ad6-842d-11e8-99be-278983068d30.png)





    Thank you so much.

**Comment by tianoak** [comment]
hello, yang,


I noticed "visual studio 2015" appearing in your error info. Does it mean you did not recompile the code in your own vs 2017? Besides, you can see the error occurred in line 175. When I tested, I tried some values for “size”. If your “size” is set too small, then the width and height will be too big, which will cause this exception. I did not figure out how to avoid this exception in addition to setting a bigger value for the parameter "size". As you can see in the readme, then I use convert( a tool, find it here https://www.imagemagick.org/script/index.php) to combine those sub-images.


Good luck.

Tian

Convert, Edit, Or Compose Bitmap Images @ ImageMagick<https://www.imagemagick.org/script/index.php>
www.imagemagick.org
ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, WebP, Postscript, PDF, and SVG.



[cid:0c049afe-0170-4e59-8e59-d70c1d057ba7]

________________________________
发件人: Merryang <notifications@github.com>
发送时间: 2018年7月10日 2:43:25
收件人: tianoak/MedicalImageFormatConvert
抄送: Huan Tian; Comment
主题: Re: [tianoak/MedicalImageFormatConvert] Fail to run ConsoleApplication1.exe on win10 x64 (#1)


[1531190500 1]<https://user-images.githubusercontent.com/36835678/42486311-008dc2fe-842e-11e8-955f-c44bc3feac02.png>
Hello Tian,
I haven't got a VS before, and following your answer, I installed the newest VS 2017 last night, and dll files can be found. However, new errors appeared, is it that I must have VS 2015 instead of VS 2017? Here is a runtime screen shot.
[image]<https://user-images.githubusercontent.com/36835678/42486264-acd10ad6-842d-11e8-99be-278983068d30.png>

Thank you so much.

**Comment by Merryang** [comment]
Hi，Tian，
Thanks a million for your valuable time, it really help a lot for a green hand in C++. I will try to modify the source code and recompile it with VS 2017. Wish everything goes well. 


Yours,
Yang


发自网易邮箱大师
On 7/10/2018 19:59，Huan Tian<notifications@github.com> wrote：
hello, yang,


I noticed "visual studio 2015" appearing in your error info. Does it mean you did not recompile the code in your own vs 2017? Besides, you can see the error occurred in line 175. When I tested, I tried some values for “size”. If your “size” is set too small, then the width and height will be too big, which will cause this exception. I did not figure out how to avoid this exception in addition to setting a bigger value for the parameter "size". As you can see in the readme, then I use convert( a tool, find it here https://www.imagemagick.org/script/index.php) to combine those sub-images.


Good luck.

Tian

Convert, Edit, Or Compose Bitmap Images @ ImageMagick<https://www.imagemagick.org/script/index.php>
www.imagemagick.org
ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, WebP, Postscript, PDF, and SVG.



[cid:0c049afe-0170-4e59-8e59-d70c1d057ba7]

________________________________
发件人: Merryang <notifications@github.com>
发送时间: 2018年7月10日 2:43:25
收件人: tianoak/MedicalImageFormatConvert
抄送: Huan Tian; Comment
主题: Re: [tianoak/MedicalImageFormatConvert] Fail to run ConsoleApplication1.exe on win10 x64 (#1)


[1531190500 1]<https://user-images.githubusercontent.com/36835678/42486311-008dc2fe-842e-11e8-955f-c44bc3feac02.png>
Hello Tian,
I haven't got a VS before, and following your answer, I installed the newest VS 2017 last night, and dll files can be found. However, new errors appeared, is it that I must have VS 2015 instead of VS 2017? Here is a runtime screen shot.
[image]<https://user-images.githubusercontent.com/36835678/42486264-acd10ad6-842d-11e8-99be-278983068d30.png>

Thank you so much.
